
[mastodon]
url = "https://mastodon.social"

# You can use the `getToken` subcommand to generate this token:
token = ""

[diskuto]
# What Diskuto server should we access?
apiUrl = "https://blog.nfnitloop.com"

[diskuto.write]
# We'll write to this user's blog.
# This should be a userID used only for this purpose, because
# we'll use its posts to know where to resume synchronization.
userID = "TODO"
password = "TODO"

